https:
  host: "0.0.0.0"
  port: "8082"
  
aws:
  accesskey: "![PrCrBZZI6T4wJMoFV50lHzYB+X8Ed9ymGqcdjoyCK3U=]"
  secretkey: "![zMfqNu0yQHuy0e/Wbm0EAAyLZtF2MSjwZH87kzckM09s32ehituC3DiUL0o1X+BT]"
  regionendpoint: "us-east-1"
 
  sqs:
    arn: "arn:aws:sqs:us-east-1:484907510455:qubotica-po-sqs"
    url: "https://sqs.us-east-1.amazonaws.com/484907510455/qubotica-po-sqs"
    
functionalIdentifier: "qbotica-po"


generic:
  maxretries: "3"
  millisecondsbetweenretries: "30000"
  
reconnection:
  freq: "3000"
  reconnectionattempts: "3"