#%RAML 1.0 NamedExample
qbotica-po-papi-example:
 [
  {
    "CUSTOMER NO": "K430",
    "CUSTOMER PO NO": "30110532_376",
    "ECT PO NUMBER": "",
    "EXPECTED SHIP DATE": "",
    "DOCK DATE": "",
    "Order Date": "02/02/2023",
    "SHIP TO NAME": "TRANE TECHNOLOGIES CO LLC",
    "SHIP TO ADDRESS": "TRANE WACO 182 COTTON BELT PKWY  MCGREGOR TX",
    "PO LINE NO": "18.6",
    "QUANTITY ORDERED": "16",
    "UNIT PRICE": "0.00",
    "CUSTOMER PART NO": "SXA029C2BPA",
    "COPELAND MODEL NO": "ZP29K5E-PFJ-303",
    "ITEM DESCRIPTION": "",
    "REJECTED MESSAGE": "DUPLICATE ORDER FOR ITEM/REQ DATE PO#"
  },
  {
    "CUSTOMER NO": "K430",
    "CUSTOMER PO NO": "30110532_376",
    "ECT PO NUMBER": "",
    "EXPECTED SHIP DATE": "",
    "DOCK DATE": "",
    "Order Date": "02/02/2023",
    "SHIP TO NAME": "TRANE TECHNOLOGIES CO LLC",
    "SHIP TO ADDRESS": "TRANE WACO 182 COTTON BELT PKWY  MCGREGOR TX",
    "PO LINE NO": "73.9",
    "QUANTITY ORDERED": "16",
    "UNIT PRICE": "0.00",
    "CUSTOMER PART NO": "X24021812030",
    "COPELAND MODEL NO": "ZP54K3E-TFD-230",
    "ITEM DESCRIPTION": "",
    "REJECTED MESSAGE": "DUPLICATE ORDER FOR ITEM/REQ DATE PO#"
  }
 ]  